services:
    gba-webserver:
        image: gba-webserver
        logging:
            options:
                max-size: '20m'
                max-file: '3'
            driver: json-file
        build:
            context: ${SERVICE_GBAJS3:-.}
            args:
                CLIENT_HOST: ${CLIENT_HOST}
        ports:
            - "443:443"
            - "80:80"
        environment:
            - CLIENT_HOST=${CLIENT_HOST}
        volumes:
            - ${CERT_LOC}:/certs/fullchain.pem
            - ${KEY_LOC}:/certs/privkey.pem