name: Gbajs3

on:
  push:
    branches: ['**']
    paths:
      - './gbajs3'
  pull_request:
    branches: ['**']
    paths:
      - './gbajs3'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          sparse-checkout: './gbajs3'
          sparse-checkout-cone-mode: false

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.1.0

      - name: Install dependencies
        run: |
          npm ci

      - name: Build
        run: |
          npm run build

      - name: Lint
        run: |
          npm run lint
